### ISSUE TITLE
Problem using image with EI with gluon.SymbolBlock.imports

### ISSUE THREAD

**Issue by anotinelg** [aws/sagemaker-mxnet-serving-container#40]
HI, 

 I used the image ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/sagemaker-mxnet-serving-eia:1.4.0-cpu-py3 to deploy a model into my Sagemaker account.
It is using a custom entry point where the model_fn looks like that:

```def model_fn(model_dir):
   ctx = mx.eia() if os.environ.get(INFERENCE_ACCELERATOR_PRESENT_ENV) == 'true' else get_default_context()

    net = gluon.SymbolBlock.imports(
        '%s/%s-symbol.json' % (model_dir, NAME_MODEL),
        ['data'],
        '%s/%s-0000.params' % (model_dir, NAME_MODEL), # load the first one, by convention it is the best
        ctx = ctx
    )


    return net
```

The endpoint is deployed like that:
```
 model.deploy(endpoint_name="test-ep",
                  initial_instance_count = 1,
                  instance_type = 'ml.c5.xlarge',
                  accelerator_type="ml.eia1.medium")
```

When I call the endpoint I have the following failure:
```
2019-07-04 22:37:24,025 [INFO ] main com.amazonaws.ml.mms.ModelServer -
MMS Home: /usr/local/lib/python3.6/site-packages
Current directory: /
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 1
Max heap size: 1844 M
Python executable: /usr/local/bin/python
Config file: /etc/sagemaker-mms.properties
Inference address: http://0.0.0.0:8080
Management address: http://127.0.0.1:8081
Model Store: /.sagemaker/mms/models
Initial Models: ALL
Log dir: /logs
Metrics dir: /logs
Netty threads: 0
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
2019-07-04 22:37:24,075 [INFO ] main com.amazonaws.ml.mms.wlm.ModelManager - Model model loaded.
2019-07-04 22:37:24,090 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2019-07-04 22:37:24,173 [INFO ] main com.amazonaws.ml.mms.ModelServer - Inference API bind to: http://0.0.0.0:8080
2019-07-04 22:37:24,173 [INFO ] main com.amazonaws.ml.mms.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2019-07-04 22:37:24,174 [INFO ] main com.amazonaws.ml.mms.ModelServer - Management API bind to: http://127.0.0.1:8081
Model server started.
2019-07-04 22:37:24,178 [WARN ] pool-2-thread-1 com.amazonaws.ml.mms.metrics.MetricCollector - worker pid is not available yet.
2019-07-04 22:37:24,216 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Listening on port: /home/model-server/tmp/.mms.sock.9000
2019-07-04 22:37:24,216 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [PID]52
2019-07-04 22:37:24,216 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - MXNet worker started.
2019-07-04 22:37:24,216 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Python runtime: 3.6.8
2019-07-04 22:37:24,219 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.mms.sock.9000
2019-07-04 22:37:24,229 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Connection accepted: /home/model-server/tmp/.mms.sock.9000.
2019-07-04 22:37:25,244 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 998
2019-07-04 22:38:08,079 [INFO ] pool-1-thread-2 ACCESS_LOG - /127.0.0.1:44598 "GET /ping HTTP/1.1" 200 33
2019-07-04 22:38:12,897 [INFO ] pool-1-thread-2 ACCESS_LOG - /127.0.0.1:44598 "GET /ping HTTP/1.1" 200 0
....
2019-07-04 22:40:57,896 [INFO ] pool-1-thread-2 ACCESS_LOG - /127.0.0.1:44598 "GET /ping HTTP/1.1" 200 0
2019-07-04 22:41:00,789 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Call model_fn
2019-07-04 22:41:02,099 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Invoking custom service failed.
2019-07-04 22:41:02,099 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mms/service.py", line 108, in predict
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ret = self._entry_point(input_batch, self.context)
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_inference/default_handler_service.py", line 31, in handle
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - return self._service.transform(data, context)
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_inference/transformer.py", line 55, in transform
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self.validate_and_initialize()
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/sagemaker_inference/transformer.py", line 94, in validate_and_initialize
2019-07-04 22:41:02,100 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self._model = self._model_fn(environment.model_dir)
2019-07-04 22:41:02,101 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/opt/ml/model/code/model_mnist.py", line 324, in model_fn
2019-07-04 22:41:02,101 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ctx = ctx
2019-07-04 22:41:02,101 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/block.py", line 1026, in imports
2019-07-04 22:41:02,101 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ret.collect_params().load(param_file, ctx=ctx)
2019-07-04 22:41:02,101 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 920, in load
2019-07-04 22:41:02,101 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self[name]._load_init(arg_dict[name], ctx)
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 257, in _load_init
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self._init_impl(data, ctx)
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 297, in _init_impl
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self._data = [data.copyto(ctx) for ctx in self._ctx_list]
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 297, in <listcomp>
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - self._data = [data.copyto(ctx) for ctx in self._ctx_list]
2019-07-04 22:41:02,102 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2077, in copyto
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - return _internal._copyto(self, out=hret)
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "<string>", line 25, in _copyto
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - ctypes.byref(out_stypes)))
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - File "/usr/local/lib/python3.6/site-packages/mxnet/base.py", line 252, in check_call
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - raise MXNetError(py_str(_LIB.MXGetLastError()))
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - **mxnet.base.MXNetError: [22:41:02] src/ndarray/ndarray.cc:1280: GPU is not enabled**
2019-07-04 22:41:02,105 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -
2019-07-04 22:41:02,106 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Stack trace returned 10 entries:
2019-07-04 22:41:02,106 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (0) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(dmlc::StackTrace()+0x44) [0x7fc36bb19494]
2019-07-04 22:41:02,106 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (1) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x21) [0x7fc36bb19871]
2019-07-04 22:41:02,106 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (2) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::CopyFromTo(mxnet::NDArray const&, mxnet::NDArray const&, int, bool)+0x723) [0x7fc36e8b1fa3]
2019-07-04 22:41:02,108 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (3) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::imperative::PushFComputeEx(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)::{lambda(mxnet::RunContext)#1}::operator()(mxnet::RunContext) const+0x110) [0x7fc36e72bfe0]
2019-07-04 22:41:02,108 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (4) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::imperative::PushFComputeEx(std::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::engine::Var*, std::allocator<mxnet::engine::Var*> > const&, std::vector<mxnet::Resource, std::allocator<mxnet::Resource> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&)+0x3ca) [0x7fc36e7376aa]
2019-07-04 22:41:02,109 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (5) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::Imperative::InvokeOp(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode, mxnet::OpStatePtr)+0x839) [0x7fc36e7203a9]
2019-07-04 22:41:02,109 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (6) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x38c) [0x7fc36e720c2c]
2019-07-04 22:41:02,109 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (7) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(MXImperativeInvokeImpl(void*, int, void**, int*, void***, int, char const**, char const**)+0x4f9) [0x7fc36e600249]
2019-07-04 22:41:02,109 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (8) /usr/local/lib/python3.6/site-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x6f) [0x7fc36e60083f]
2019-07-04 22:41:02,109 [INFO ] W-9000-model-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - [bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fc3762e0e40]
2019-07-04 22:41:02,112 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 1324
2019-07-04 22:41:02,114 [INFO ] W-9000-model ACCESS_LOG - /127.0.0.1:44598 "POST /invocations HTTP/1.1" 503 1329
2019-07-04 22:41:02,909 [INFO ] pool-1-thread-2 ACCESS_LOG - /127.0.0.1:44852 "GET /ping HTTP/1.1" 200 0
2019-07-04 22:41:07,896 [INFO ] pool-1-thread-2 
```

Any ideas, of what it is going on? Is it possible to use Elastic Inference with 1.4.0 framework? 
Thank you

Nota: I use gluon to do training, and the models and params files are exported like that:

```
net.export('%s/%s'% (model_dir, NAME_MODEL), epoch=0) 
```

**Comment by laurenyu** [comment]
apologies for the late response

it looks like the error is "mxnet.base.MXNetError: [22:41:02] src/ndarray/ndarray.cc:1280: GPU is not enabled" from the stacktrace. Do you have anything in your entry point code that could be trying to configure something GPU-related?

**Comment by laurenyu** [comment]
closing due to lack of activity. feel free to reopen if necessary.
